apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sympo-demo-svc
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sympo-demo-svc
          servicePort: 3000